'use client';
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'mr' | 'hi';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Branding & Common
    appName: "VariVerse",
    appSubtitle: "Vari Pilgrimage Management System",
    welcome: "Welcome",
    signOut: "Sign Out",
    devotionalGreeting: "Jai Hari Vitthal! 🙏",
    language: "Language",
    english: "English",
    marathi: "मराठी (Marathi)",
    hindi: "हिंदी (Hindi)",
    
    // NGO Dashboard
    ngoDashboard: "NGO Dashboard",
    resourceCoordination: "Resource Coordination",
    navigation: "Navigation",
    foodCentres: "Food Centres",
    waterPoints: "Water Points",
    shelterCapacity: "Shelter Capacity",
    helpRequestsLabel: "Help Requests",
    foodDistribution: "Food Distribution",
    served: "Served:",
    openStatus: "OPEN",
    closedStatus: "CLOSED",
    shelterStatus: "Shelter Status",
    spaceStatus: "SPACE",
    fullStatus: "FULL",
    occupied: "occupied",
    mapView: "Map View",
    volunteersLabel: "Volunteers",
    resourcesLabel: "Resources",
    
    // Subpages
    foodSub: "NGO — Manage all Annadan food centres",
    openCentres: "Open Centres",
    closedCentres: "Closed",
    totalServed: "Total Served",
    totalCapacity: "Total Capacity",
    queue: "Queue:",
    hygiene: "Hygiene:",
    closeBtn: "Close",
    openBtn: "Open",
    waterDistribution: "Water Supply",
    waterSub: "NGO — Manage drinking water points",
    drinking: "Drinking",
    filtered: "Filtered",
    tanker: "Tanker",
    refillRequired: "Refill Required",
    available: "Available",
    sheltersDistribution: "Shelters",
    sheltersSub: "NGO — Manage all dormitories and rest camps",
    spacesAvailable: "Spaces Available",
    
    // Dynamic Data

    // Firebase New Names
    "Seva Jal Booth": "Seva Jal Booth",
    "Mauli Jal Kendra": "Mauli Jal Kendra",
    "Highway Water Station": "Highway Water Station",
    "Route Water Kiosk B": "Route Water Kiosk B",
    "Route Water Kiosk A": "Route Water Kiosk A",
    "Emergency Water Tanker 1": "Emergency Water Tanker 1",
    "Bhima River Water Point": "Bhima River Water Point",
    "Warkari Pyaav 1": "Warkari Pyaav 1",
    "Pandharpur Water Booth 1": "Pandharpur Water Booth 1",
    "Panduranga Jalaseva": "Panduranga Jalaseva",
    "Seva Water Point B": "Seva Water Point B",
    "Medical Camp Water": "Medical Camp Water",
    "Village Water Booth": "Village Water Booth",
    "Community Water Hub": "Community Water Hub",
    "Temple Water Point": "Temple Water Point",
    "Vithal Annadan Kendra": "Vithal Annadan Kendra",
    "Rukhmini Bhojanalaay": "Rukhmini Bhojanalaay",
    "Sant Tukaram Prasad": "Sant Tukaram Prasad",
    "Mauli Annadan Trust": "Mauli Annadan Trust",
    "Warkari Seva Bhojan": "Warkari Seva Bhojan",
    "Panduranga Annadan": "Panduranga Annadan",
    "Dnyaneshwar Prasadalay": "Dnyaneshwar Prasadalay",
    "Namdev Bhojan Griha": "Namdev Bhojan Griha",
    "Sopandev Annadan": "Sopandev Annadan",
    "Changdev Seva Kendra": "Changdev Seva Kendra",
    "Muktabai Bhojan Trust": "Muktabai Bhojan Trust",
    "Janabai Annadan Sewa": "Janabai Annadan Sewa",
    "Eknath Maharaj Prasad": "Eknath Maharaj Prasad",
    "Tukaram Maharaj Annadan": "Tukaram Maharaj Annadan",
    "Bahina Bai Seva": "Bahina Bai Seva",
    "Vitthal Bhakta Niwas": "Vitthal Bhakta Niwas",
    "Warkari Dharamshala": "Warkari Dharamshala",
    "Seva Niwas 1": "Seva Niwas 1",
    "Pandharpur Choultry": "Pandharpur Choultry",
    "Bhima Kinari Niwas": "Bhima Kinari Niwas",
    "Sant Tukaram Kutir": "Sant Tukaram Kutir",
    "Mauli Seva Niwas": "Mauli Seva Niwas",
    "Panduranga Ashram": "Panduranga Ashram",
    "Route Rest Camp A": "Route Rest Camp A",
    "Emergency Shelter Hub": "Emergency Shelter Hub",
    
    // Roles
    varkari: "Varkari Pilgrim",
    volunteer: "Volunteer",
    medicalTeam: "Medical Team",
    police: "Police / Security",
    ngo: "NGO",
    serviceProvider: "Service Provider",
    cleaner: "Sanitation Staff",
    admin: "Admin",

    // Navigation Labels
    home: "Home",
    map: "Pilgrimage Map",
    smartSos: "Emergency SOS",
    wariConnect: "Vari Connect",
    food: "Annadan & Food",
    water: "Water Supply",
    medical: "Medical Camps",
    shelter: "Shelter & Stay",
    toilets: "Sanitation",
    wellness: "Foot Care & Wellness",
    lostFound: "Lost & Found",
    alerts: "Safety Alerts",
    dashboard: "Dashboard",
    sosIncidents: "SOS Incidents",
    helpRequests: "Help Requests",
    lostPersons: "Missing Persons",
    community: "Community Feed",
    crowdReports: "Crowd Density",
    emergencyQueue: "Emergency Queue",
    camps: "Medical Camps",
    ambulance: "Ambulance",
    cases: "Case Records",
    crowdAlerts: "Crowd Alerts",
    routeAlerts: "Route Advisories",
    foodDist: "Food Distribution",
    waterDist: "Water Distribution",
    volunteers: "Volunteers",
    resources: "Resources",
    charging: "Charging Points",
    cleaningLog: "Cleaning Log",
    issues: "Reported Issues",
    commandCenter: "Command Center",
    totalVarkaris: "Total Varkaris",
    activeVolunteers: "Active Volunteers",
    securityPersonnel: "Security Personnel",
    medicalStaff: "Medical Staff",
    liveSOS: "Live SOS Feed",
    crowdZones: "Crowd Zones",
    missingPersons: "Missing Persons",
    activity: "Vari Connect Activity",
    onPilgrimage: "On pilgrimage today",
    activeSOS: "Active SOS",
    totalIncidents: "total incidents",
    redZones: "Red Zones",
    totalZones: "total zones",
    availableNow: "Available now",
    situationalAwareness: "Real-time situational awareness",
    viewAll: "View All",
    moderate: "Moderate",
    aiPredict: "AI Predict",
    sanitationReportsTitle: "Sanitation Reports (CleanWari)",
    noSanitationIncidents: "No recent sanitation incidents reported.",
    locationPrefix: "Location:",
    unknownBlock: "Unknown Block",
    notesPrefix: "Notes:",
    noDetails: "No additional details",
    noWater: "NO WATER",
    searchByEmail: "Search by email...",
    addNew: "Add New",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    role: "Role",
    name: "Name",
    email: "Email",
    status: "Status",
    actions: "Actions",
    priority: "Priority",
    location: "Location",
    capacity: "Capacity",
    reportedBy: "Reported By",
    date: "Date",
    description: "Description",
    systemEvents: "System Events",
    mapLayers: "Map Layers",
    liveTraffic: "Live Traffic",
    resourceAllocation: "Resource Allocation",
    crowdDensityForecast: "Crowd Density Forecast",
    runModel: "Run Model",
    systemHealth: "System Health",
    activeSessions: "Active Sessions",
    approve: "Approve",
    reject: "Reject",
    found: "Found",

    needsCleaning: "NEEDS CLEANING",
    overflow: "OVERFLOW",
    damaged: "DAMAGED",
    statusReported: "REPORTED",
    statusAssigned: "ASSIGNED",




    digitalTwin: "Digital Twin",
    analytics: "Analytics",
    aiPredictions: "AI Predictions",
    users: "User Directory",
    feedback: "Feedback",
    reports: "Reports",
    demoControl: "Practical Working",

    // Actions & Buttons
    refresh: "Refresh",
    cancel: "Cancel",
    submit: "Submit",
    accept: "Accept",
    resolve: "Mark Resolved",
    acknowledge: "Acknowledge",
    inProgressBtn: "In Progress",
    all: "All",
    statusCreated: "CREATED",
    statusAck: "ACKNOWLEDGED",
    statusInProgress: "IN PROGRESS",
    statusResolved: "RESOLVED",

    details: "View Details",
    filter: "Filter",
    search: "Search",
    openNow: "Open Now",
    closed: "Closed",
    urgent: "Urgent",
    signIn: "Sign In",
    signInDescription: "Enter your authorized credentials to access the platform",
    emailAddress: "Email Address",
    password: "Password",
    quickAccess: "Quick Access Portal",
    quickAccessDescription: "Select a stakeholder role to inspect the live dashboard",
    demonstrationFlow: "Demonstration Flow",
    loginAs: "Login as",
    viewServices: "view services and test Smart SOS",
    inspectMap: "inspect the Live Digital Twin map",
    defaultDemoPassword: "Default Demo Password",
    directions: "Get Directions",
  },
  mr: {
    // Branding & Common
    appName: "VariVerse",
    appSubtitle: "पंढरपूर वारी व्यवस्थापन प्रणाली",
    welcome: "सुस्वागतम",
    signOut: "बाहेर पडा",
    devotionalGreeting: "जय हरी विठ्ठल! 🙏",
    language: "भाषा",
    english: "English",
    marathi: "मराठी",
    hindi: "हिंदी",
    
    // NGO Dashboard
    ngoDashboard: "एनजीओ डॅशबोर्ड",
    resourceCoordination: "संसाधन समन्वय",
    navigation: "नेव्हिगेशन",
    foodCentres: "अन्नछत्र केंद्रे",
    waterPoints: "जल केंद्रे",
    shelterCapacity: "निवारा क्षमता",
    helpRequestsLabel: "मदतीची विनंती",
    foodDistribution: "अन्नछत्र वितरण",
    served: "दिले:",
    openStatus: "सुरू",
    closedStatus: "बंद",
    shelterStatus: "निवारा स्थिती",
    spaceStatus: "जागा आहे",
    fullStatus: "पूर्ण भरले",
    occupied: "भरलेले",
    mapView: "नकाशा पहा",
    volunteersLabel: "स्वयंसेवक",
    resourcesLabel: "संसाधने",
    
    // Subpages
    foodSub: "एनजीओ - सर्व अन्नछत्रांचे व्यवस्थापन करा",
    openCentres: "सुरू केंद्रे",
    closedCentres: "बंद",
    totalServed: "एकूण दिले",
    totalCapacity: "एकूण क्षमता",
    queue: "रांग:",
    hygiene: "स्वच्छता:",
    closeBtn: "बंद करा",
    openBtn: "सुरू करा",
    waterDistribution: "पाणीपुरवठा",
    waterSub: "एनजीओ - पिण्याच्या पाण्याची केंद्रे व्यवस्थापित करा",
    drinking: "पिण्याचे",
    filtered: "फिल्टर्ड",
    tanker: "टँकर",
    refillRequired: "रिफिल आवश्यक",
    available: "उपलब्ध",
    sheltersDistribution: "निवारा",
    sheltersSub: "एनजीओ - सर्व धर्मशाळा आणि विश्रांती शिबिरांचे व्यवस्थापन करा",
    spacesAvailable: "जागा उपलब्ध",
    
    // Dynamic Data

    // Firebase New Names
    "Seva Jal Booth": "सेवा जल बूथ",
    "Mauli Jal Kendra": "माउली जल केंद्र",
    "Highway Water Station": "महामार्ग जल केंद्र",
    "Route Water Kiosk B": "रूट जल किओस्क बी",
    "Route Water Kiosk A": "रूट जल किओस्क ए",
    "Emergency Water Tanker 1": "आपत्कालीन पाण्याचा टँकर १",
    "Bhima River Water Point": "भीमा नदी जल केंद्र",
    "Warkari Pyaav 1": "वारकरी प्याऊ १",
    "Pandharpur Water Booth 1": "पंढरपूर जल केंद्र १",
    "Panduranga Jalaseva": "पांडुरंग जलसेवा",
    "Seva Water Point B": "सेवा जल केंद्र बी",
    "Medical Camp Water": "मेडिकल कॅम्प पाणी",
    "Village Water Booth": "गाव जल बूथ",
    "Community Water Hub": "सामुदायिक जल केंद्र",
    "Temple Water Point": "मंदिर जल केंद्र",
    "Vithal Annadan Kendra": "विठ्ठल अन्नदान केंद्र",
    "Rukhmini Bhojanalaay": "रुक्मिणी भोजनालय",
    "Sant Tukaram Prasad": "संत तुकाराम प्रसाद",
    "Mauli Annadan Trust": "माउली अन्नदान ट्रस्ट",
    "Warkari Seva Bhojan": "वारकरी सेवा भोजन",
    "Panduranga Annadan": "पांडुरंग अन्नदान",
    "Dnyaneshwar Prasadalay": "ज्ञानेश्वर प्रसादालय",
    "Namdev Bhojan Griha": "नामदेव भोजन गृह",
    "Sopandev Annadan": "सोपानदेव अन्नदान",
    "Changdev Seva Kendra": "चांगदेव सेवा केंद्र",
    "Muktabai Bhojan Trust": "मुक्ताबाई भोजन ट्रस्ट",
    "Janabai Annadan Sewa": "जनाबाई अन्नदान सेवा",
    "Eknath Maharaj Prasad": "एकनाथ महाराज प्रसाद",
    "Tukaram Maharaj Annadan": "तुकाराम महाराज अन्नदान",
    "Bahina Bai Seva": "बहिणाबाई सेवा",
    "Vitthal Bhakta Niwas": "विठ्ठल भक्त निवास",
    "Warkari Dharamshala": "वारकरी धर्मशाळा",
    "Seva Niwas 1": "सेवा निवास १",
    "Pandharpur Choultry": "पंढरपूर चोल्ट्री",
    "Bhima Kinari Niwas": "भीमा किनारी निवास",
    "Sant Tukaram Kutir": "संत तुकाराम कुटीर",
    "Mauli Seva Niwas": "माउली सेवा निवास",
    "Panduranga Ashram": "पांडुरंग आश्रम",
    "Route Rest Camp A": "रूट रेस्ट कॅम्प ए",
    "Emergency Shelter Hub": "आपत्कालीन निवारा केंद्र",
    
    // Roles
    varkari: "वारकरी भक्त",
    volunteer: "स्वयंसेवक",
    medicalTeam: "वैद्यकीय पथक",
    police: "पोलीस सुरक्षा",
    ngo: "NGO",
    serviceProvider: "सेवा पुरवठादार",
    cleaner: "स्वच्छता कर्मचारी",
    admin: "Admin",

    // Navigation Labels
    home: "मुख्य पृष्ठ",
    map: "वारी नकाशा",
    smartSos: "तातडीची मदत (SOS)",
    wariConnect: "वारी कनेक्ट",
    food: "अन्नदान व भोजन",
    water: "पिण्याचे पाणी",
    medical: "वैद्यकीय केंद्र",
    shelter: "निवास व धर्मशाळा",
    toilets: "शौचालय सुविधा",
    wellness: "पाय सेवा व आरोग्य",
    lostFound: "हरवले-सापडले",
    alerts: "सुरक्षा सूचना",
    dashboard: "डॅशबोर्ड",
    sosIncidents: "आणीबाणी घटना",
    helpRequests: "मदतीचे अर्ज",
    lostPersons: "हरवलेल्या व्यक्ती",
    community: "समुदाय संवाद",
    crowdReports: "गर्दी अहवाल",
    emergencyQueue: "आणीबाणी रांग",
    camps: "वैद्यकीय छावण्या",
    ambulance: "रुग्णवाहिका",
    cases: "रुग्ण नोंदी",
    crowdAlerts: "गर्दी इशारे",
    routeAlerts: "मार्ग सूचना",
    foodDist: "अन्न वितरण",
    waterDist: "जल वितरण",
    volunteers: "स्वयंसेवक",
    resources: "साहित्य व संसाधने",
    charging: "चार्जिंग केंद्र",
    cleaningLog: "स्वच्छता नोंदवही",
    issues: "नोंदवलेल्या अडचणी",
    commandCenter: "मुख्य नियंत्रण केंद्र",
    totalVarkaris: "एकूण वारकरी",
    activeVolunteers: "सक्रिय स्वयंसेवक",
    securityPersonnel: "सुरक्षा रक्षक",
    medicalStaff: "वैद्यकीय कर्मचारी",
    liveSOS: "थेट आपत्कालीन (SOS)",
    crowdZones: "गर्दीचे ठिकाणे",
    missingPersons: "हरवलेल्या व्यक्ती",
    activity: "वारी कनेक्ट घडामोडी",
    onPilgrimage: "आज वारीमध्ये",
    activeSOS: "सक्रिय SOS",
    totalIncidents: "एकूण घटना",
    redZones: "लाल क्षेत्रे (धोकादायक)",
    totalZones: "एकूण क्षेत्रे",
    availableNow: "सध्या उपलब्ध",
    situationalAwareness: "रिअल-टाइम परिस्थिती जाणीव",
    viewAll: "सर्व पहा",
    moderate: "नियंत्रण करा",
    aiPredict: "AI अंदाज",
    sanitationReportsTitle: "स्वच्छता अहवाल (क्लीनवारी)",
    noSanitationIncidents: "नुकत्याच नोंदवलेल्या स्वच्छता घटना नाहीत.",
    locationPrefix: "ठिकाण:",
    unknownBlock: "अज्ञात ब्लॉक",
    notesPrefix: "नोंदी:",
    noDetails: "कोणतीही अतिरिक्त माहिती नाही",
    noWater: "पाणी नाही",
    searchByEmail: "ईमेलद्वारे शोधा...",
    addNew: "नवीन जोडा",
    edit: "संपादित करा",
    delete: "काढून टाका",
    save: "जतन करा",
    role: "भूमिका",
    name: "नाव",
    email: "ईमेल",
    status: "स्थिती",
    actions: "कृती",
    priority: "प्राधान्य",
    location: "ठिकाण",
    capacity: "क्षमता",
    reportedBy: "नोंदवणारे",
    date: "तारीख",
    description: "वर्णन",
    systemEvents: "सिस्टम घटना",
    mapLayers: "नकाशा स्तर",
    liveTraffic: "थेट वाहतूक",
    resourceAllocation: "संसाधन वाटप",
    crowdDensityForecast: "गर्दीचा अंदाज",
    runModel: "मॉडेल चालवा",
    systemHealth: "सिस्टम आरोग्य",
    activeSessions: "सक्रिय सत्रे",
    approve: "मंजूर करा",
    reject: "नाकारा",
    found: "सापडले",

    needsCleaning: "स्वच्छता आवश्यक",
    overflow: "पाणी साचले आहे",
    damaged: "नुकसान",
    statusReported: "नोंदवले",
    statusAssigned: "नेमून दिले",




    digitalTwin: "डिजिटल नकाशा (Live)",
    analytics: "आकडेवारी विश्लेषण",
    aiPredictions: "AI अंदाज",
    users: "वापरकर्ते सूची",
    feedback: "अभिप्राय",
    reports: "अहवाल",
    demoControl: "डेमो नियंत्रण",

    // Actions & Buttons
    refresh: "ताजे करा",
    cancel: "रद्द करा",
    submit: "सबमिट करा",
    accept: "स्वीकारा",
    resolve: "पूर्ण झाले",
    acknowledge: "नोंद घ्या",
    inProgressBtn: "प्रगतीपथावर",
    all: "सर्व",
    statusCreated: "नोंदवली",
    statusAck: "पाहिली",
    statusInProgress: "काम चालू",
    statusResolved: "पूर्ण",

    details: "तपशील पहा",
    filter: "गाळून पहा",
    search: "शोधा",
    openNow: "सुरू आहे",
    closed: "बंद आहे",
    urgent: "तातडीचे",
    signIn: "प्रवेश करा",
    signInDescription: "प्लॅटफॉर्मवर प्रवेश करण्यासाठी अधिकृत माहिती भरा",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    quickAccess: "जलद प्रवेश पोर्टल",
    quickAccessDescription: "डॅशबोर्ड पाहण्यासाठी भूमिका निवडा",
    demonstrationFlow: "प्रात्यक्षिक क्रम",
    loginAs: "याप्रमाणे प्रवेश",
    viewServices: "सेवा पहा आणि स्मार्ट SOS तपासा",
    inspectMap: "लाइव्ह डिजिटल नकाशा पहा",
    defaultDemoPassword: "डेमोचा डीफॉल्ट पासवर्ड",
    directions: "दिशा मिळवा",
  },
  hi: {
    // Branding & Common
    appName: "VariVerse",
    appSubtitle: "वारकरी यात्रा प्रबंधन प्रणाली",
    welcome: "स्वागत है",
    signOut: "साइन आउट करें",
    devotionalGreeting: "जय हरी विट्ठल! 🙏",
    language: "भाषा",
    english: "English",
    marathi: "मराठी",
    hindi: "हिंदी",
    
    // NGO Dashboard
    ngoDashboard: "एनजीओ डैशबोर्ड",
    resourceCoordination: "संसाधन समन्वय",
    navigation: "नेविगेशन",
    foodCentres: "भोजन केंद्र",
    waterPoints: "जल केंद्र",
    shelterCapacity: "आवास क्षमता",
    helpRequestsLabel: "सहायता अनुरोध",
    foodDistribution: "भोजन वितरण",
    served: "परोसा गया:",
    openStatus: "खुला है",
    closedStatus: "बंद है",
    shelterStatus: "आवास स्थिति",
    spaceStatus: "जगह है",
    fullStatus: "पूर्ण",
    occupied: "भरा हुआ",
    mapView: "मानचित्र दृश्य",
    volunteersLabel: "स्वयंसेवक",
    resourcesLabel: "संसाधन",
    
    // Subpages
    foodSub: "एनजीओ - सभी अन्नदान केंद्रों का प्रबंधन करें",
    openCentres: "खुले केंद्र",
    closedCentres: "बंद",
    totalServed: "कुल परोसा गया",
    totalCapacity: "कुल क्षमता",
    queue: "कतार:",
    hygiene: "स्वच्छता:",
    closeBtn: "बंद करें",
    openBtn: "खोलें",
    waterDistribution: "पानी की आपूर्ति",
    waterSub: "एनजीओ - पीने के पानी के केंद्रों का प्रबंधन करें",
    drinking: "पीने का",
    filtered: "फ़िल्टर्ड",
    tanker: "टैंकर",
    refillRequired: "रीफिल आवश्यक",
    available: "उपलब्ध",
    sheltersDistribution: "आश्रय",
    sheltersSub: "एनजीओ - सभी धर्मशालाओं और विश्राम शिविरों का प्रबंधन करें",
    spacesAvailable: "स्थान उपलब्ध",
    
    // Dynamic Data

    // Firebase New Names
    "Seva Jal Booth": "सेवा जल बूथ",
    "Mauli Jal Kendra": "माउली जल केंद्र",
    "Highway Water Station": "राजमार्ग जल केंद्र",
    "Route Water Kiosk B": "रूट जल कियोस्क बी",
    "Route Water Kiosk A": "रूट जल कियोस्क ए",
    "Emergency Water Tanker 1": "आपातकालीन पानी का टैंकर १",
    "Bhima River Water Point": "भीमा नदी जल केंद्र",
    "Warkari Pyaav 1": "वारकरी प्याऊ १",
    "Pandharpur Water Booth 1": "पंढरपुर जल केंद्र १",
    "Panduranga Jalaseva": "पांडुरंग जलसेवा",
    "Seva Water Point B": "सेवा जल केंद्र बी",
    "Medical Camp Water": "चिकित्सा शिविर पानी",
    "Village Water Booth": "गाँव जल बूथ",
    "Community Water Hub": "सामुदायिक जल केंद्र",
    "Temple Water Point": "मंदिर जल केंद्र",
    "Vithal Annadan Kendra": "विट्ठल अन्नदान केंद्र",
    "Rukhmini Bhojanalaay": "रुक्मिणी भोजनालय",
    "Sant Tukaram Prasad": "संत तुकाराम प्रसाद",
    "Mauli Annadan Trust": "माउली अन्नदान ट्रस्ट",
    "Warkari Seva Bhojan": "वारकरी सेवा भोजन",
    "Panduranga Annadan": "पांडुरंग अन्नदान",
    "Dnyaneshwar Prasadalay": "ज्ञानेश्वर प्रसादालय",
    "Namdev Bhojan Griha": "नामदेव भोजन गृह",
    "Sopandev Annadan": "सोपानदेव अन्नदान",
    "Changdev Seva Kendra": "चांगदेव सेवा केंद्र",
    "Muktabai Bhojan Trust": "मुक्ताबाई भोजन ट्रस्ट",
    "Janabai Annadan Sewa": "जनाबाई अन्नदान सेवा",
    "Eknath Maharaj Prasad": "एकनाथ महाराज प्रसाद",
    "Tukaram Maharaj Annadan": "तुकाराम महाराज अन्नदान",
    "Bahina Bai Seva": "बहिणाबाई सेवा",
    "Vitthal Bhakta Niwas": "विट्ठल भक्त निवास",
    "Warkari Dharamshala": "वारकरी धर्मशाला",
    "Seva Niwas 1": "सेवा निवास १",
    "Pandharpur Choultry": "पंढरपुर चोल्ट्री",
    "Bhima Kinari Niwas": "भीमा किनारी निवास",
    "Sant Tukaram Kutir": "संत तुकाराम कुटीर",
    "Mauli Seva Niwas": "माउली सेवा निवास",
    "Panduranga Ashram": "पांडुरंग आश्रम",
    "Route Rest Camp A": "रूट रेस्ट कैंप ए",
    "Emergency Shelter Hub": "आपातकालीन आश्रय केंद्र",
    
    // Roles
    varkari: "वारकरी श्रद्धालु",
    volunteer: "सेवक / स्वयंसेवक",
    medicalTeam: "चिकित्सा टीम",
    police: "पुलिस सुरक्षा",
    ngo: "NGO",
    serviceProvider: "सेवा प्रदाता",
    cleaner: "स्वच्छता कर्मी",
    admin: "Admin",

    // Navigation Labels
    home: "मुख्य पृष्ठ",
    map: "यात्रा मानचित्र",
    smartSos: "आपातकालीन SOS",
    wariConnect: "वारी कनेक्ट",
    food: "अन्नदान व भोजन",
    water: "पेयजल सुविधा",
    medical: "चिकित्सा शिविर",
    shelter: "आवास व विश्राम",
    toilets: "शौचालय सुविधा",
    wellness: "चरण सेवा व स्वास्थ्य",
    lostFound: "खोया-पाया",
    alerts: "सुरक्षा अलर्ट",
    dashboard: "डैशबोर्ड",
    sosIncidents: "आपातकालीन घटनाएं",
    helpRequests: "सहायता अनुरोध",
    lostPersons: "लापता व्यक्ति",
    community: "समुदाय संवाद",
    crowdReports: "भीड़ रिपोर्ट",
    emergencyQueue: "आपातकालीन कतार",
    camps: "चिकित्सा शिविर",
    ambulance: "एम्बुलेंस सेवा",
    cases: "मामलों का विवरण",
    crowdAlerts: "भीड़ चेतावनी",
    routeAlerts: "मार्ग सलाह",
    foodDist: "भोजन वितरण",
    waterDist: "जल वितरण",
    volunteers: "स्वयंसेवक",
    resources: "संसाधन व सामग्री",
    charging: "चार्जिंग प्वाइंट",
    cleaningLog: "सफाई लॉग",
    issues: "दर्ज समस्याएं",
    commandCenter: "कमांड सेंटर",
    totalVarkaris: "कुल वारकरी",
    activeVolunteers: "सक्रिय स्वयंसेवक",
    securityPersonnel: "सुरक्षा कर्मी",
    medicalStaff: "चिकित्सा कर्मचारी",
    liveSOS: "लाइव आपातकालीन (SOS)",
    crowdZones: "भीड़ वाले क्षेत्र",
    missingPersons: "लापता व्यक्ति",
    activity: "वारी कनेक्ट गतिविधि",
    onPilgrimage: "आज यात्रा में",
    activeSOS: "सक्रिय SOS",
    totalIncidents: "कुल घटनाएं",
    redZones: "रेड जोन (खतरनाक)",
    totalZones: "कुल क्षेत्र",
    availableNow: "अभी उपलब्ध",
    situationalAwareness: "वास्तविक समय स्थिति जागरूकता",
    viewAll: "सभी देखें",
    moderate: "नियंत्रण करें",
    aiPredict: "AI भविष्यवाणी",
    sanitationReportsTitle: "स्वच्छता रिपोर्ट (क्लीनवारी)",
    noSanitationIncidents: "हाल ही में कोई स्वच्छता घटना दर्ज नहीं की गई है।",
    locationPrefix: "स्थान:",
    unknownBlock: "अज्ञात ब्लॉक",
    notesPrefix: "टिप्पणियाँ:",
    noDetails: "कोई अतिरिक्त विवरण नहीं",
    noWater: "पानी नहीं",
    searchByEmail: "ईमेल द्वारा खोजें...",
    addNew: "नया जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    save: "सहेजें",
    role: "भूमिका",
    name: "नाम",
    email: "ईमेल",
    status: "स्थिति",
    actions: "कार्रवाई",
    priority: "प्राथमिकता",
    location: "स्थान",
    capacity: "क्षमता",
    reportedBy: "रिपोर्टकर्ता",
    date: "तारीख",
    description: "विवरण",
    systemEvents: "सिस्टम ईवेंट",
    mapLayers: "मानचित्र परतें",
    liveTraffic: "लाइव ट्रैफ़िक",
    resourceAllocation: "संसाधन आवंटन",
    crowdDensityForecast: "भीड़ घनत्व पूर्वानुमान",
    runModel: "मॉडल चलाएं",
    systemHealth: "सिस्टम स्वास्थ्य",
    activeSessions: "सक्रिय सत्र",
    approve: "मंजूर करें",
    reject: "अस्वीकार करें",
    found: "मिल गया",

    needsCleaning: "सफाई आवश्यक",
    overflow: "पानी भर गया",
    damaged: "क्षतिग्रस्त",
    statusReported: "दर्ज की गई",
    statusAssigned: "सौंप दिया गया",




    digitalTwin: "डिजिटल मानचित्र (Live)",
    analytics: "विश्लेषण व आंकड़े",
    aiPredictions: "AI भविष्यवाणी",
    users: "उपयोगकर्ता सूची",
    feedback: "फीडबैक",
    reports: "रिपोर्ट",
    demoControl: "डेमो नियंत्रण",

    // Actions & Buttons
    refresh: "रिफ्रेश करें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    accept: "स्वीकार करें",
    resolve: "हल हुआ",
    acknowledge: "संज्ञान लें",
    inProgressBtn: "प्रगति पर",
    all: "सभी",
    statusCreated: "दर्ज की गई",
    statusAck: "संज्ञान लिया",
    statusInProgress: "प्रगति पर",
    statusResolved: "हल हो गई",

    details: "विवरण देखें",
    filter: "फ़िल्टर",
    search: "खोजें",
    openNow: "खुला है",
    closed: "बंद है",
    urgent: "अत्यंत आवश्यक",
    signIn: "साइन इन करें",
    signInDescription: "प्लेटफ़ॉर्म तक पहुंचने के लिए अधिकृत जानकारी दर्ज करें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    quickAccess: "त्वरित प्रवेश पोर्टल",
    quickAccessDescription: "डैशबोर्ड देखने के लिए भूमिका चुनें",
    demonstrationFlow: "प्रदर्शन क्रम",
    loginAs: "इस रूप में प्रवेश",
    viewServices: "सेवाएं देखें और स्मार्ट SOS जांचें",
    inspectMap: "लाइव डिजिटल मानचित्र देखें",
    defaultDemoPassword: "डेमो का डिफ़ॉल्ट पासवर्ड",
    directions: "दिशा देखें",
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  tn: (num: number | string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
  tn: (num: number | string) => String(num),
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>('mr'); // Default to Marathi for Varkari audience

  useEffect(() => {
    const saved = localStorage.getItem('wv_lang') as Language;
    if (saved && (saved === 'en' || saved === 'mr' || saved === 'hi')) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('wv_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const tn = (num: number | string): string => {
    if (lang === 'en') return String(num);
    const numMap: Record<string, string> = {
      '0': '०', '1': '१', '2': '२', '3': '३', '4': '४',
      '5': '५', '6': '६', '7': '७', '8': '८', '9': '९'
    };
    return String(num).replace(/[0-9]/g, match => numMap[match]);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tn }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
